name: "작업 요청"
description: "새로운 작업을 위한 이슈를 생성합니다."
title: "[작업] "
labels: []
assignees: []

body:
  - type: dropdown
    id: branch_type
    attributes:
      label: "브랜치 타입 선택 (prefix)"
      description: "작업 유형을 선택하세요. (예: feature, fix, style)"
      options:
        - "feature"
        - "fix"
        - "style"
      default: "feature"

  - type: input
    id: branch_suffix
    attributes:
      label: "브랜치 이름 (접미사, suffix)"
      description: "브랜치 이름의 마지막 부분을 입력하세요. (예: login-button-bug, add-user-auth)"
      placeholder: "login-button-bug"

  - type: markdown
    attributes:
      value: "**🔹 최종 브랜치 이름 예시:** `[선택한 브랜치 타입]/[입력한 접미사]` → `feature/login-button-bug`"
