name: "Create Issue Branch"

on:
  issues:
    types: [assigned] # 이슈가 'Assigned'되면 실행
  issue_comment:
    types: [created] # 이슈에 댓글이 추가되면 실행 가능
  pull_request:
    types: [closed] # PR이 닫히면 실행 (선택 사항)

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
